spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
server:
  port: 8001
spring:
  application:
    name: bill-provider
  datasource:
    url: jdbc:mysql://192.168.10.11:3306/springcloud_db01?serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      min-idle: 5                                
      initial-size: 5                            
      max-total: 5                               
      max-wait-millis: 150                       
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  type-aliases-package: com.mengxuegu.bill.entities

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.1.109:6001/eureka,http://192.168.1.109:6002/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
