spring:
  profiles:
    active: dev
---
server:
  port: 6001
spring:
  profiles: dev
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://192.168.10.12:6002/eureka
  server:
    enable-self-preservation: false
  instance:
    hostname: eureka6001.com
---
server:
  port: 6011
spring:
  profiles: proc
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://192.168.10.12:6012/eureka
  server:
    enable-self-preservation: false
  instance:
    hostname: eureka6011.com
